### ISSUE TITLE
precisazione 3.15

### ISSUE THREAD

**Issue by fuomag9** [lnwor/dirInfo#1]
Precisare anche che l'autorizzazione include anche chi detetiene il diritto all'esecuzione di una copia del programma (e.g. lo ha comprato)

si veda comma a, L. 22 aprile 1941, n. 633, art 64 quater

`le predette attività siano eseguite dal licenziatario o da altri che abbia il diritto di usare una copia del programma oppure, per loro conto, da chi è autorizzato a tal fine`

**Comment by lorenzo9uerra** [comment]
Penso che sia già chiaro, in quanto dice:
```
Questo è possibile a patto che:
• Le attività sono compiute dal licenziatario o soggetto autorizzato
```
che include appunto chi detiene il diritto all'esecuzione di una copia del programma.
Però inserisco anche questo per completezza, grazie.
